export const publicationSourceEnum = {
  PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET',
  AUTHOR_PUBLICATION_ENTRY: 'AUTHOR_PUBLICATION_ENTRY',
  JOURNAL_CITATION_LIST: 'JOURNAL_CITATION_LIST',
} as const

export type PublicationSourceEnum = (typeof publicationSourceEnum)[keyof typeof publicationSourceEnum]

/**
 * @description Defines the source of the publication. In general, a publication\non Google Scholar has two forms:\n* Appearing as a PUBLICATION SNIPPET and\n* Appearing as a paper in an AUTHOR PAGE\n\n------------\n\n\"PUBLICATION SEARCH SNIPPET\".\nThis form captures the publication  when it appears as a \"snippet\" in\nthe context of the resuls of a publication search. For example:\n\nPublication search: https://scholar.google.com/scholar?hl=en&q=adaptive+fraud+detection&btnG=&as_sdt=0%2C33\n\nThe entries appear under the <div class = \"gs_r gs_or gs_scl\"> tags\nEach entry has a data-cid attribute (e.g., data-cid=\"pthm1bWT96oJ\")\n\nThe same type of results will also appear when someome searches\nusing the \"cited by\", \"related articles\", and \"all XX versions\" links\nthat appear under the publication snippet.\n\n\"Cited By\" link: https://scholar.google.com/scholar?cites=12319477714873931942&as_sdt=5,33&sciodt=0,33&hl=en\n\n\"Related Articles\" link: https://scholar.google.com/scholar?q=related:pthm1bWT96oJ:scholar.google.com/&scioq=adaptive+fraud+detection&hl=en&as_sdt=0,33\n\n\"All versions\" link: https://scholar.google.com/scholar?cluster=12319477714873931942&hl=en&as_sdt=0,33\n\nThe snippet version of these publications contain the information that appears in the results.\nOften, the snippet version will miss authors, will have an abbreviated name for the venue, and so on.\n\nWe can fill these snippets by clicking on the \"Cite\" button\" and get back the MLA/APA/Chicago/...\ncitations forms, PLUS links for BibTeX, EndNote, RefMan, and RefWorks.\n\n------------\n\"AUTHOR PUBLICATION ENTRY\"\n\nWe also have publications that appear in the \"author pages\" of Google Scholar.\nThese publications are often a set of publications \"merged\" together.\n\nThe snippet version of these publications conains the title of the publication,\na subset of the authors, the (sometimes truncated) venue, and the year of the publication\nand the number of papers that cite the publication.\n\nThe snippet entries appear under the <tr class=\"gsc_a_tr\"> entries in the main page of the author.\n\nTo fill in the publication, we open the \"detailed view\" of the paper\n\nDetailed view page: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=-Km63D4AAAAJ:d1gkVwhDpl0C
 */
export type PublicationSource = PublicationSourceEnum