# fly.toml app configuration file generated for pt-server on 2025-04-13T21:51:22-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pt-server'
primary_region = 'gig'

[build]

[env]
  DB_PATH = '/data/db/fly.db'
  TOKENIZERS_PARALLELISM = 'true'

[[mounts]]
  source = 'db_volume'
  destination = '/data/db'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
